### ISSUE TITLE
Add bot commands list in README

### ISSUE THREAD

**Issue by askfriends** [xixugi/eunhamirror#3]
FIrst of all thanks a ton for additional features and hopefully will work without any issues.
I didnt see bot commands list in readme, will you add all commands so that we can copy paste in botfather.
Thanks

**Comment by xixugi** [comment]
the command is automatically added to the bot, why should you put it in the readme?

**Comment by askfriends** [comment]
> the command is automatically added to the bot, why should you put it in the readme?

I didnt know that, well its good then.
thanks
