### ISSUE TITLE
App got Suspended after deploying to Heroku

### ISSUE THREAD

**Issue by askfriends** [xixugi/eunhamirror#4]
My app was suspended after deployed to heroku??
so we cant deploy to heroku?

**Comment by xixugi** [comment]
do you have screen shot or something?

But, If you have such problem, I suggest using cli method.
I always use that way

**Comment by vincreator** [comment]
if you have issue like that
try use cli method

**Comment by askfriends** [comment]
> do you have screen shot or something?
> 
> But, If you have such problem, I suggest using cli method.
> I always use that way

Yeah here it is. My app got suspended not account.  I'm going to try cli method and will update u.
![suspended](https://user-images.githubusercontent.com/2517219/128238059-ef08e537-dfa9-4a8a-b003-f25aeaede52b.jpg)

**Comment by askfriends** [comment]
cli method also not working, got suspended immediately after deploying.

**Comment by xixugi** [comment]
thanks for the report.
I will find out what the problem is and work on it tomorrow

**Comment by askfriends** [comment]
> thanks for the report.
> I will find out what the problem is and work on it tomorrow

best of luck

**Comment by xixugi** [comment]
Done You can deploy now
